# Site settings
title: Open Source Tech for Hydrology
email: haran.kiruba@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    A blog to document my open source workflow for hydrology research.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: kirubaharanj
github_username: Kirubaharan 

# Build settings
markdown: kramdown
highlighter: pygments
